### ISSUE TITLE
The guide for setting up destinations using bulk listed in the readme appears to be incorrect.

### ISSUE THREAD

**Issue by katahiro-github** [blastengineMania/blastengine-node#1]
This link introduces the use of a method called `setTo()` when setting a destination using bulk, but as far as I can see inside `bulk.ts`, I think `addTo()` is correct.

https://github.com/blastengineMania/blastengine-node#update--add-delivery-address-to-bulk

**Comment by goofmint** [comment]
@katahiro-github Thank you for your feedback! I'll update a document soon!
